version: '3.8'

services:
  api:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: node-api
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    environment:
      - NODE_ENV=development
    env_file:
      - app/.env
    restart: unless-stopped 