version: "3.8"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "2222:2222"
    volumes:
      - ./app:/usr/src/node-api/app
      - /usr/src/node-api/app/node_modules
      - ./.ssh/authorized_keys:/root/.ssh/authorized_keys:ro
    environment:
      - NODE_ENV=production
      - TZ=Asia/Seoul
    env_file:
      - app/.env
    mem_limit: 1g
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: sh -c "/usr/sbin/sshd && cd /usr/src/node-api/app && npm install && pm2-runtime start app.js --name node-api"

