version: "3.8"

services:
  node-api:
    build: .
    container_name: node-api
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - TZ=Asia/Seoul
    env_file:
      - app/.env
    command: sh -c "cd /usr/src/app && npm install && node app.js"
    mem_limit: 1g
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

